### ISSUE TITLE
gui doesn't start

### ISSUE THREAD

**Issue by Itai-Nelken** [techcoder20/ThemeSaver#1]
```bash
pi@raspberrypi:~ $ python3 /home/$USER/ThemeSaver/gui.py
Traceback (most recent call last):
  File "/home/pi/ThemeSaver/gui.py", line 3, in <module>
    from PIL import ImageTk,Image
ImportError: cannot import name 'ImageTk' from 'PIL' (/usr/lib/python3/dist-packages/PIL/__init__.py)
pi@raspberrypi:~ $
```

also: 
```bash
pi@raspberrypi:~ $ themesaver
bash: themesaver: command not found
pi@raspberrypi:~ $ 
```

**Comment by techcoder20** [comment]
Oh ya I forgot to add some dependencies for tkinter:
`sudo apt install python-pil.imagetk python3-pil python3-pil.imagetk`

Also can you check if a alias is created for themesaver.

**Comment by Itai-Nelken** [comment]
>Also can you check if a alias is created for themesaver.

yes, there is one:
```bash
alias themesaver='python3 ~/ThemeSaver/ThemeSaver.py'
```

also once I installed the dependencies it started working!
thanks for making this great app!

**Comment by techcoder20** [comment]
Thx is it working properly ?

**Comment by Itai-Nelken** [comment]
> Thx is it working properly ?

it only saves names with no spaces, no big deal but worth a mention in the readme.
it doesn't revert to the stock theme I saved once I themed (I might be misunderstanding how it works).
btw I'm on stock 32bit RPiOS.

**Comment by techcoder20** [comment]
Yes I will be fixing the first issue soon whereas for the other one the problem is that when u don't customize anything and use the stock for raspi os no configs are generated which can be a problem. The default configs are stored somewhere in /etc/xdg or somewhere. For the time being the fix can be that I remove the existing configs so that it falls back to the default ones. I will implement the fix soon. Thanks a lot for the valuable bug report 🙂

**Comment by Itai-Nelken** [comment]
@techcoder20 after reverting back manually to the default theme, saving it, and theming again, it works as you said.
also I don't know why, but I couldn't restore minimized windows, and the panel stayed at the bottom instead of the top. I had to run `lxpanelctl retsart` to be able to restore minimized windows.

**Comment by Itai-Nelken** [comment]
>also I don't know why, but I couldn't restore minimized windows, and the panel stayed at the bottom instead of the top. I had to run lxpanelctl retsart to be able to restore minimized windows.

nvm, it was a problem on my side I think.

**Comment by Itai-Nelken** [comment]
@techcoder20 here is a screen recording, it works really great.

https://user-images.githubusercontent.com/70802936/109670375-ba328900-7b7b-11eb-87c7-e394154d3acb.mp4

**Comment by Itai-Nelken** [comment]
you should add ThemeSaver to pi-apps.

**Comment by techcoder20** [comment]
> you should add ThemeSaver to pi-apps.

Once i fix the bugs, Sure. Any feedback for the gui ?

**Comment by Itai-Nelken** [comment]
> Once i fix the bugs, Sure. Any feedback for the gui ?

its looks really nice and works really well.
