### ISSUE TITLE
exporting slots doesn't work

### ISSUE THREAD

**Issue by Itai-Nelken** [techcoder20/ThemeSaver#2]
a pop-up window says its in `/home/pi/ThemeSaver/export/<file>`, but that doesn't exist.
(`<file>` is not what actually appeared on the pop-up window)

**Comment by Itai-Nelken** [comment]
nvm, just read the README, sorry.

**Comment by techcoder20** [comment]
Strange I added a popup telling that export and import slot are not ready for LXDE

**Comment by Itai-Nelken** [comment]
maybe you accidentally made it check for `LXDE` instead of `LXDE-pi`?
