### ISSUE TITLE
install.py completes, does not launch from shortcut.

### ISSUE THREAD

**Issue by epic2342342** [techcoder20/themesaver#9]
install.py output:

`[relax@relax-laptop build]$ wget -qO- https://raw.githubusercontent.com/techcoder20/ThemeSaver/main/install.py | python3
SSL_INIT

Checking if your Desktop environment and Window manager is supported
[sudo] password for relax: 
resolving dependencies...
looking for conflicting packages...

Package (1)       New Version  Net Change  Download Size

community/wmctrl  1.07-6         0.04 MiB       0.02 MiB

Total Download Size:   0.02 MiB
Total Installed Size:  0.04 MiB

:: Proceed with installation? [Y/n] 
:: Retrieving packages...
 wmctrl-1.07-6-x86_64 downloading...
checking keyring...
checking package integrity...
loading package files...
checking for file conflicts...
:: Processing package changes...
installing wmctrl...
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
Your Desktop Environment and Window Manager Is Supported

=========[ Installing Dependencies ]=========
warning: imagemagick-7.1.0.23-1 is up to date -- skipping
resolving dependencies...
looking for conflicting packages...

Package (3)                       New Version     Net Change  Download Size

community/scrot                   1.7-1             0.11 MiB       0.07 MiB
community/ttf-ubuntu-font-family  0.83-7            3.95 MiB       1.50 MiB
community/xdotool                 3.20211022.1-1    0.18 MiB       0.07 MiB

Total Download Size:   1.63 MiB
Total Installed Size:  4.24 MiB

:: Proceed with installation? [Y/n] 
:: Retrieving packages...
 ttf-ubuntu-font-family-0.83-7-any downloading...
 scrot-1.7-1-x86_64 downloading...
 xdotool-3.20211022.1-1-x86_64 downloading...
checking keyring...
checking package integrity...
loading package files...
checking for file conflicts...
:: Processing package changes...
installing xdotool...
installing ttf-ubuntu-font-family...
installing scrot...
:: Running post-transaction hooks...
(1/4) Arming ConditionNeedsUpdate...
(2/4) Updating fontconfig configuration...
(3/4) Updating fontconfig cache...
(4/4) Updating 32-bit fontconfig cache...

=========[ Cloning Github Repo ]=========
Cloning into '/home/relax/.themesaver'...
remote: Enumerating objects: 436, done.
remote: Counting objects: 100% (436/436), done.
remote: Compressing objects: 100% (304/304), done.
remote: Total 436 (delta 248), reused 242 (delta 128), pack-reused 0
Receiving objects: 100% (436/436), 49.26 MiB | 15.43 MiB/s, done.
Resolving deltas: 100% (248/248), done.

=========[ Generating Required Files ]=========
Installing Icons
mkdir: cannot create directory ‘/home/relax/.local/share/icons’: File exists
Creating Desktop Entry
mkdir: cannot create directory ‘/home/relax/.local/share/applications’: File exists

Creating Default Configs

=========[ Installing Python Package ]=========
Installing package with pip
Defaulting to user installation because normal site-packages is not writeable
Obtaining file:///home/relax/.themesaver
/usr/lib/python3.10/site-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 2.0.5-build-libtorrent-rasterbar-src-libtorrent-rasterbar-2.0.5-bindings-python is an invalid version and will not be supported in a future release
  warnings.warn(
Requirement already satisfied: Click in /home/relax/.local/lib/python3.10/site-packages (from themesaver==2.0.0) (8.0.3)
WARNING: Keyring is skipped due to an exception: g-dbus-error-quark: The name org.freedesktop.secrets was not provided by any .service files (2)
Collecting pyqt5
  Downloading PyQt5-5.15.6-cp36-abi3-manylinux1_x86_64.whl (8.3 MB)
     |████████████████████████████████| 8.3 MB 2.4 MB/s            
Collecting python-dotenv
  Downloading python_dotenv-0.19.2-py2.py3-none-any.whl (17 kB)
Collecting tqdm
  Downloading tqdm-4.62.3-py2.py3-none-any.whl (76 kB)
     |████████████████████████████████| 76 kB 4.9 MB/s             
Collecting PyQt5-sip<13,>=12.8
  Downloading PyQt5_sip-12.9.1-cp310-cp310-manylinux1_x86_64.whl (351 kB)
     |████████████████████████████████| 351 kB 13.6 MB/s            
Collecting PyQt5-Qt5>=5.15.2
  Downloading PyQt5_Qt5-5.15.2-py3-none-manylinux2014_x86_64.whl (59.9 MB)
     |████████████████████████████████| 59.9 MB 143 kB/s             
Installing collected packages: PyQt5-sip, PyQt5-Qt5, tqdm, python-dotenv, pyqt5, themesaver
  WARNING: The script tqdm is installed in '/home/relax/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script dotenv is installed in '/home/relax/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts pylupdate5, pyrcc5 and pyuic5 are installed in '/home/relax/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Running setup.py develop for themesaver
Successfully installed PyQt5-Qt5-5.15.2 PyQt5-sip-12.9.1 pyqt5-5.15.6 python-dotenv-0.19.2 themesaver tqdm-4.62.3

Finished Installing Themesaver`

**Comment by techcoder20** [comment]
Hmm the problem is that ~/.local/bin is not on your path. Can you please mention which shell you are currently using ?

**Comment by epic2342342** [comment]
Hey there, thanks for the tip, I'll add it to my path. My shell at the moment is bash.

**Comment by techcoder20** [comment]
Hmm it should have worked it was bash. Nvm I just found the bug and fixed it. If you run the install script again it should add `~/.local/bin` to your path.

**Comment by epic2342342** [comment]
You got it, thanks mate
